### PR TITLE
*: support keys get options.

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @disksing

### CODE REVIEW

**Comment by ngaut** [comment]
cc @xiang90

**Comment by xiang90** [comment]
have you tried https://github.com/gengo/grpc-gateway? We plan to use this library. Here is an example: https://github.com/philips/grpc-gateway-example.

**Comment by siddontang** [comment]
No, we haven't. 

@xiang90 What's your progress for supporting gateway with this lib?  If you will do soon, I think we can wait and still use this simple HTTP gateway now, otherwise, we can try to implement this feature and send a PR. 

How do you think, @ngaut .

**Comment by siddontang** [comment]
@xiang90 

I discussed it with @ngaut, and we decide to wait your support later, so we will use this simple gateway now because what we want is very simple, just getting data from etcd.

**Comment by xiang90** [comment]
sure

**Comment by disksing** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
